#!/bin/bash
wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | gpg --dearmor | tee /etc/apt/trusted.gpg.d/anydesk.gpg > /dev/null
echo -e "#Anydesk\n\
Types: deb\n\
URIs: http://deb.anydesk.com/\n\
Suites: all\n\
Components: main\n\
Signed-By: /etc/apt/trusted.gpg.d/anydesk.gpg" | tee /etc/apt/sources.list.d/anydesk-stable.sources
