#!/bin/bash
wget -qO - https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg > /dev/null

# MS Edge
echo -e "#Brave Browser\n\
Types: deb\n\
URIs: https://brave-browser-apt-release.s3.brave.com\n\
Suites: stable\n\
Components: main\n\
Signed-By: /etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg\n\
Architectures: amd64" | tee /etc/apt/sources.list.d/brave-browser.sources
