#!/bin/bash
wget -qO - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

# MS Edge
echo -e "#MS Edge\n\
Types: deb\n\
URIs: https://packages.microsoft.com/repos/edge\n\
Suites: stable\n\
Components: main\n\
Signed-By: /etc/apt/trusted.gpg.d/microsoft.gpg\n\
Architectures: amd64" | tee /etc/apt/sources.list.d/microsoft-edge.sources

# VS Code
echo -e "#VS Code\n\
Types: deb\n\
URIs: http://packages.microsoft.com/repos/code\n\
Suites: stable\n\
Components: main\n\
Signed-By: /etc/apt/trusted.gpg.d/microsoft.gpg\n\
Architectures: amd64,arm64,armhf" | tee /etc/apt/sources.list.d/vscode.sources
