#!/bin/sh
set -e

case "$1" in
    configure)
    if which plank >/dev/null 2>&1
    then
        cp /etc/mamolinux/net.launchpad.plank.gschema.xml /usr/share/glib-2.0/schemas
    fi
    if which glib-compile-schemas >/dev/null 2>&1
    then
        glib-compile-schemas /usr/share/glib-2.0/schemas
    fi
    if which cp >/dev/null 2>&1
    then
        cp /etc/mamolinux/grub /etc/default/
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
